/* 
  File: _data/cms.js
  Description: DEPRECATED - Use cms-data.json instead (generated by fetch-cms-data.js)
  
  This file is kept for reference but is no longer used.
  The CMS data is now fetched by running "node fetch-cms-data.js" before build.
  
  Author: Sai Trivedi
  Updated: 2025-11-14
*/

export default function () {
  console.log("⚠️  cms.js is deprecated - using cms-data.json instead");
  return { movies: [] };
}
